# Generated by Django 4.2.7 on 2023-11-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
