# Generated by Django 4.2.7 on 2023-11-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historicalperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='items',
            field=models.CharField(max_length=100),
        ),
    ]
